---
title: "Assignment-4 part-1"
author: "Teja Sri"
date: "2025-09-19"
output:
  pdf_document: default
  html_document: default
---

```{r Downloading the Gene Expression contains RNA Sequence count}
# Gene expression file
url_gene <- "https://raw.githubusercontent.com/ghazkha/Assessment4/refs/heads/main/gene_expression.tsv"
download.file(url_gene, destfile = "gene_expression.tsv", mode = "wb")
gene <- read.delim("gene_expression.tsv", row.names = 1, check.names = FALSE)
head(gene)
```

```{r Downloading growth data containing measurements for the tree circumference growing at two sites}

# Growth data file
url_growth <- "https://raw.githubusercontent.com/ghazkha/Assessment4/refs/heads/main/growth_data.csv"
download.file(url_growth, destfile = "growth_data.csv", mode = "wb")
growth <- read.csv("growth_data.csv", check.names = FALSE)
head(growth)
```

```{r Gene expression Analysis}
## 1. Show first six genes
# Display the first six rows of the dataset (gene expression counts).
head(gene)
```


```{r Gene expression Analysis}
## 2. Add mean column
# Calculate the mean expression across the three samples for each gene.
# Store it in a new column called "mean_expr".
gene$mean_expr <- rowMeans(gene)

# Show the first six rows again, now including the new column.
head(gene)
```


```{r Gene expression Analysis}
## 3. Top 10 genes by mean expression
# Order the genes by descending mean expression and select the top 10.
top10 <- head(gene[order(-gene$mean_expr), ], 10)
top10
```


```{r Gene expression Analysis}
## 4. Number of genes with mean < 10
# Count how many genes have a mean expression value less than 10.
n_low <- sum(gene$mean_expr < 10)
n_low
```


```{r Gene expression Analysis}
## 5. Histogram of mean values
# Plot a histogram to visualize the distribution of mean gene expression values.
hist(gene$mean_expr, 
     breaks = 40, 
     main = "Histogram of mean gene expression", 
     xlab = "Mean expression")
```

```{r Growth data analysis}
# Inspect column names
colnames(growth)

# Define Start and End explicitly from the available columns
growth$Start <- growth$Circumf_2005_cm
growth$End   <- growth$Circumf_2020_cm

## 1) Column names (already printed by colnames)
# colnames(growth)
gene <- read.delim("gene_expression.tsv", row.names = 1, check.names = FALSE)
head(gene)
```
```{r}
## --- Prepare convenient Start/End columns (from the year columns) ---
growth$Start <- growth$Circumf_2005_cm
growth$End   <- growth$Circumf_2020_cm

## --- 2) Mean and SD at Start and End by Site (PRINT BOTH) ---
by_start <- aggregate(Start ~ Site, data = growth,
                      FUN = function(x) c(mean = mean(x, na.rm = TRUE),
                                          sd   = sd(x,   na.rm = TRUE)))
by_end   <- aggregate(End ~ Site, data = growth,
                      FUN = function(x) c(mean = mean(x, na.rm = TRUE),
                                          sd   = sd(x,   na.rm = TRUE)))

start_stats <- cbind(Site = by_start$Site, as.data.frame(by_start$Start))
end_stats   <- cbind(Site = by_end$Site,   as.data.frame(by_end$End))
colnames(start_stats)[2:3] <- c("mean_start","sd_start")
colnames(end_stats)[2:3]   <- c("mean_end","sd_end")

start_stats   # <-- keep this printed
end_stats     # <-- and this printed
```


```{r}
## --- 3) Boxplots (Start vs End by Site) ---
par(mfrow = c(1,2))
boxplot(Start ~ Site, data = growth,
        main = "Tree circumference at Start (2005)", ylab = "Circumference (cm)")
boxplot(End   ~ Site, data = growth,
        main = "Tree circumference at End (2020)",  ylab = "Circumference (cm)")
par(mfrow = c(1,1))
```


```{r}
## --- 4) Mean growth over the LAST 10 YEARS (2010 -> 2020) ---
growth$growth10 <- growth$Circumf_2020_cm - growth$Circumf_2010_cm

## site means (and SD if you want)
tapply(growth$growth10, growth$Site, mean, na.rm = TRUE)
# If you also want SD:
tapply(growth$growth10, growth$Site, sd, na.rm = TRUE)
```


```{r}
## --- 5) t-test: is 10-year growth different between sites? ---
t.test(growth$growth10 ~ growth$Site)

```

